M48
; DRILL file KiCad 10.0.1 date 2026-06-06T15:16:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T15:16:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X59.0Y-58.0
X59.0Y-122.0
X141.0Y-58.0
X141.0Y-122.0
T2
X84.251Y-61.956
M30
